### PR TITLE
Added Journalism++

### PR DESCRIPTION
**Pull request by pirhoo**
Journalism++ asks candidates to solve riddles in order to apply and demonstrate their skills.

### CODE REVIEW

**Comment by poteto** [comment]
Hi, sorry but we consider riddles to be part of the "whiteboard" experience

**Comment by pirhoo** [comment]
OK, no problem! For the record: those riddles are takehome exercises and definitely real world problems (we do use technical skills to investigate on daily basis). 

Best, Pierre

**Comment by poteto** [comment]
@pirhoo I see, I apologize that I didn't read the page you linked. In this case it looks like they're relevant to the job so it's 👍. I would however rephrase "riddles" since that might have a negative connotation.

**Comment by pirhoo** [comment]
Amazing! Thanks

**Pull request merged**
