### PR TITLE
Adding a relevant article

### PR DESCRIPTION
**Pull request by jesalg**
Adding a relevant article which was on the HackerNews front page recently: https://news.ycombinator.com/item?id=35031474

## Add/Update/Remove <CompanyName>

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [x] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

### CODE REVIEW

**Comment by ma8642** [comment]
@poteto I leave this one for you, as the contribution guidelines don't cover this kind of addition.

**Comment by jesalg** [comment]
FWIW that blog post links to this repo so would be nice to have a reference back!

**Comment by jesalg** [comment]
Bump @ma8642 @poteto

**Comment by poteto** [comment]
@jesalg thanks for the mention! I was originally intending to keep the links section for "official" discussions from the team, but I don't see why that should be the case anymore.

bors r+

**Comment by jesalg** [comment]
Sounds great, thanks @poteto!

**Pull request merged**
