### PR TITLE
Removed Dead Links, Sold Companies, and fixed dead job links

### PR DESCRIPTION
**Pull request by alecdesjardins**
Some the career links were dead, so I swapped to their main pages. There were a few companies that had been bought out.

## Add/Update/Remove <CompanyName>

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [ ] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

### CODE REVIEW

**Review by poteto — APPROVED** [review]
Thanks!

**Comment by alecdesjardins** [comment]
@poteto should I merge? I will go through the rest of the links at some point and attempt to get most of them fixed or removed.

**Comment by poteto** [comment]
@alecdesjardins yup, I trust you!

**Comment by banjaminlee** [comment]
Hi @poteto

https://bold.pro/my/banjamin-lee-241212153841

This is my resume.
I want to work for you.
I look forward your reply.

**Comment by szepeviktor** [comment]
@alecdesjardins Could you includes these please?

```
error: `tehnical` should be `technical`
  --> ./README.md:516:91
    |
516 | - [Locastic](https://www.locastic.com/posao) | Split, Croatia | Take-home code challenge, tehnical discussion & on-site programming session, meet & greet with the team
    |                                                                                           ^^^^^^^^
    |
error: `regardnig` should be `regarding`
  --> ./README.md:769:141
    |
769 | - [Sendyne](https://www.sendyne.com) | New York City, USA | Phone screen, on-site with team members. Review of past experiences + questions regardnig real problems.
    |                                                                                                                                             ^^^^^^^^^
    |
error: `Melborne` should be `Melbourne`
  --> ./README.md:955:35
    |
955 | - [Xplor](https://ourxplor.com) | Melborne, Australia; London, UK | Phone Cultural Fit interview, Take home-code challenge, pair-programming session and discussion about past experience
    |                                   ^^^^^^^^
    |
```

**Comment by alecdesjardins** [comment]
@szepeviktor Typo changes were included. Thanks for letting me know!

**Comment by szepeviktor** [comment]
@alecdesjardins Thank you.

The first two turned out to be "ourne"

**Pull request merged**
