### PR TITLE
Remove Centroida

### PR DESCRIPTION
**Pull request by ma8642**
## Remove Centroida

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [x] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

Centroida has been acquired by the company Scalefocus.

### CODE REVIEW

**Comment by ma8642** [comment]
@poteto Despite being a collaborator, it looks like you need to also give me permission for bors specifically.

**Comment by poteto** [comment]
@ma8642 oops, try again?

**Pull request merged**
