### PR TITLE
Update Cognitech Inc. & Plane link

### PR DESCRIPTION
**Pull request by TahaHameed23**
## Update <Cognitech Inc.>

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [ ] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

The old link gives 404: 
https://www.cognitect.com/jobs (Cognitech )
https://plane.com/become-a-partner (Plane)

Updated link ( by Cognitech & Plane ): 
https://international.nubank.com.br/careers/  (Cognitech )
https://pilot.notion.site/Plane-Careers-Page-0f9a2b64ddd8470f968335b769de0909   (Plane)

### CODE REVIEW

**Comment by alecdesjardins** [comment]
Cognitect should be removed. They were acquired by Nu, which is a company already listed.

**Comment by TahaHameed23** [comment]
@alecdesjardins , Changed as you mentioned-
1. Removed Cognitech
2. Renamed Pilot to <b>Plane</b>

**Comment by alecdesjardins** [comment]
@TahaHameed23 Thanks for contributing! Plane will need to be moved into alphabetical order.

**Comment by TahaHameed23** [comment]
'Plane' is now in alphabetical order.

**Pull request merged**
