### PR TITLE
Remove Aurora Solar

### PR DESCRIPTION
**Pull request by JamieVaughn**
I interviewed at Aurora Solar about 3 months ago. They use a whiteboarding session. Seems like they're calling it "pair programming" but it's not that... the other person just asked a few questions and sat silently as I coded the solution.... so not pair programming. It's a white boarding session.

## Add/Update/Remove <CompanyName>

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [x] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

### CODE REVIEW

**Comment by JamieVaughn** [comment]
The session that they call "pair programming" is actually a white boarding session. It takes place after the byteboard.dev take home assignment (which I thought was actually quite good!). The white boarding session uses a shared online code editor like coderpad and they ask you to solve some arbitrary coding problems on the spot.

**Comment by cherscarlett** [comment]
> The session that they call "pair programming" is actually a white boarding session. It takes place after an initial zoom interview with some verbal/conceptual web development questions (which I thought was actually quite good!). The white boarding session uses a shared online code editor like coderpad and they ask you to solve some arbitrary coding problems on the spot.

Can you clarify what type of coding was involved, and why you believe it's comparably to white-boarding?

**Comment by jessethach** [comment]
I can second this removal. I had preliminary interview sessions with them last year and they required exactly what @JamieVaughn stated.

It’s comparable due to the fact that it requires live coding. This may require a more holistic conversation about what white boarding culture actually entails. I personally feel that live coding falls in this realm. The physical whiteboard is taken away, but the gatekeeing culture is still there.

**Comment by cherscarlett** [comment]
I'm not sure that live coding has traditionally been excluded here, @poteto, thoughts?

**Comment by jessethach** [comment]
Putting someone on the spot to code when being watched feels like the same situation as whiteboarding. When it’s done in a virtual space vs a physical one feels arbitrary to me.

**Comment by cherscarlett** [comment]
@jessethach To be clear, I'm not disagreeing with the idea of it. I have ADHD and I'm bipolar type I. I won't do live coding and strongly shout about it on Twitter. I'm just trying to adhere to the rules here and I don't think live coding has been a reason to deny, unless it's arbitrary algorithms and such, like a whiteboard. That's why I asked for clarification and @poteto's opinion.

**Comment by jessethach** [comment]
@cherscarlett Gotcha - appreciate the clarification!

**Comment by JamieVaughn** [comment]
Sorry about my delayed response (I somehow just got notified about activity here and missed the comments from several weeks ago)


@cherscarlett  To clarify the type of live coding they do, I can only speak about my particular case. They asked me to write a function that found all strings in an array that contained a given substring passed in as a parameter with case sensitivity. Then they asked me to write an input debounce function without using lodash or a library or looking at any resources. 

To me the nature of asking to recreate a solved thing that is easily supported by common tools in the ecosystem (i.e. debounce function) is what gave it the white boarding atmosphere.

**Comment by cherscarlett** [comment]
Thank you @JamieVaughn!! I agree with your assessment, so I'll go ahead and merge this. Thank you for taking the time. 🌮

**Pull request merged**
