### PR TITLE
Add Stripe

### PR DESCRIPTION
**Pull request by marianosimone**
## Add/Update/Remove <CompanyName>

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [x] In your pull request message, add additional context on the interview process if necessary **N/A**

### CODE REVIEW

**Comment by marianosimone** [comment]
@poteto, looks good now!

**Comment by pdb64** [comment]
@marianosimone, both times I interviewed at Stripe (once in 2017, once in 2018) they used whiteboard interview questions. Is this a changed policy as of 2019?

**Comment by marianosimone** [comment]
I interviewed in Dec '18, joined in Jan '19, and I'm still at Stripe and conducting interviews: all programming exercises were and are still done "with your own laptop/setup and full access to internet"

**Comment by pdb64** [comment]
@marianosimone interesting, I had a leetcode style interview with them (wasn't leetcode, but some competitor I'm forgetting the name of). Do leetcode style interviews not count as "whiteboard"?

**Comment by marianosimone** [comment]
From the readme on this page:

> Discussing a real world problem (with or without whiteboard) is 👍
> Solving CS trivia, technical puzzles, riddles, brainteasers (with or without whiteboard) is 👎

None of the interview question Stripe does today (and, at least to Dec 2018) fall in the CS trivia, technical puzzles, riddles, brainteasers category.

The tool Stripe uses for sharing interview questions is CoderPad, not sure if you are referring to that.

**Pull request merged**
