### PR TITLE
Added Hackerrank, updated readme

### PR DESCRIPTION
**Pull request by yuvi17**
Added details for Hackerrank hiring process based on my recent experience. The interview included a simple test on Hackerrank, followed by something called as RBA. I was given a question to design and implement a set of APIs, which can be pushed and tested on Hackerrank platform via Git. The face-to-face round included a discussion on past work and projects, a system design round, a value/culture-fit round and discussion with CEO.

## Add/Update/Remove <CompanyName>

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [x] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

### CODE REVIEW

**Comment by yuvi17** [comment]
@poteto any comments on this

**Comment by renannprado** [comment]
Isn't it weird that this company wants to be in this repo?

**Comment by cheesesashimi** [comment]
From the README:

> Using sites like HackerRank/LeetCode _probably_ fall into a similar category.

I think the use of HackerRank / LeetCode / et. al. should disqualify a company from being listed in this repo. Many of the problems I've seen on those platforms are more akin to brainteasers, riddles or an automated whiteboarding session as opposed to a real-world situation. In addition, I think automated tests such as the ones provided by HackerRank cause more problems than they solve.

Because of that and HackerRank's mission, I do not think they should be included in this repo. Although I have permissions to approve / reject PRs, I will defer to @poteto for the final decision since this is her project.

**Comment by yuvi17** [comment]
Hi @cheesesashimi @poteto @renannprado 
First of all, this PR should be considered from a fellow software engineer and not from the company (otherwise it would have been raised by the company GitHub account).

Also, you raised many points about a lot of problems being brain-teasers and I agree with the fact. However, that is not the mission of the company as many wrongly believe (even I did too.) The motto is to match every developer with the right job. 

In my personal interview, I was not asked any brain-teasers. The coding questions were not something that you won't encounter in day-to-day life ( invert a binary tree fame etc.).

However, my biggest reason for this PR will be [(https://blog.hackerrank.com/new-role-based-assessments)/]

Hackerrank as a company realizes CS 101 kind of challenges are not the way to hire people and for my interview, they treated me with the same line of thought. I was given a take-home assignment to design a set of APIs for a streak based submission system (similar to GitHub). There were test-cases for the API that had to be passed.  After that, there was a code-review with one of the employees. There were no white-board components (apart from white-boarding a system design).

Hence this PR, since they (we may be) as a company(and probably the only one) are investing in doing away with puzzles and brain-teasers and including real-world questions. I experienced it first hand.

**Comment by yuvi17** [comment]
@poteto @cheesesashimi @renannprado any updates?

**Comment by renannprado** [comment]
IMO, if a company is supporting the broken hiring process of other companies, then it doesn't belong here.
Not sure what the others think.

**Pull request closed without merging**
