### PR TITLE
added readify

### PR DESCRIPTION
**Pull request by ghuntley**

### CODE REVIEW

**Comment by poteto** [comment]
I'm not quite sure if technical puzzles are that different from CS questions on a whiteboard

**Comment by ghuntley** [comment]
It's quite literally FizzBuzz + WordReversal + Deploy your API. To call it a puzzle is a stretch, the process is very different. Complete knock knock, we will do a quick verification check that you wrote your own code/debugging excercise, then management interview. Done. It's all documented publically.

**Comment by ghuntley** [comment]
@poteto could you please review https://github.com/poteto/hiring-without-whiteboards/pull/24#issuecomment-286676194 

Thanks :)

**Comment by poteto** [comment]
I consider FizzBuzz + WordReversal and other kinds of similar problems as disqualifiers, sorry!

**Pull request closed without merging**
