### PR TITLE
Remove Facebook as they practice white-boarding

### PR DESCRIPTION
**Pull request by JulienDefrance**
Interviewed in Menlo Park in 2018. The technical interview was absolutely impersonal, consisted in the typical white boarding exercise, with the same questions around time and space complexity.

## Add/Update/Remove <CompanyName>

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [x] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

Interviewed in Menlo Park in 2018. The technical interview was absolutely impersonal, consisted in the typical white boarding exercise, with the same questions around time and space complexity.

### CODE REVIEW

**Review by Gimhan-minion — APPROVED** [review]

**Comment by poteto** [comment]
I think this is very likely true for the general SWE interview, but the Front End Engineer interview (which I did) is quite different.  See this [tweet for an example](https://twitter.com/dan_abramov/status/1095133998584602626). That's the one listed here.

**Comment by alecdesjardins** [comment]
@poteto does Meta still hire frontend engineers only? I had a screening call with a Meta recruiter last week, and she said there are very few, if any at all, front-end only engineers being hired.

The general SWE is very much white boarding and does not fit the criteria of this repo.

**Comment by ulgens** [comment]
Facebook is one of the hardest pushers for whiteboard-style interviews. Their own study materials tell you to prepare for leet code style questions, and they ask you to solve them live in the meeting, in the very first step of the technical interview. It feels weird and misleading to have them here.

**Comment by poteto** [comment]
@alecdesjardins the role and specialized hiring process still exists, but I'm not sure if there are still teams hiring for it at the moment. That could change over time.

**Pull request closed without merging**
