### PR TITLE
Fix Truora website URL

### PR DESCRIPTION
**Pull request by aledeltoro**
## Update Truora

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [ ] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

## Context
The URL for Truora's website was broken. This PR updates the URL.

### CODE REVIEW

**Comment by poteto** [comment]
Thanks! However, not everyone speaks English: I think it's fine to link directly to the main page and let people decide what language they want to read it in.

**Comment by aledeltoro** [comment]
Good point @poteto ! I will make the adjustment. However, the main reason I was making the change was because the current URL is missing the `www` prefix, due to that the URL is broken. Sorry for the misunderstanding on the purpose of the PR.

**Comment by poteto** [comment]
Ah yeah that makes sense. Thanks for the PR!

bors r+

**Pull request merged**
