### PR TITLE
Adding company Pilot

### PR DESCRIPTION
**Pull request by staszek**
## Add Pilot

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines

### CODE REVIEW

**Comment by poteto** [comment]
What does the remote interview entail?

**Comment by staszek** [comment]
@poteto I added some details about the process

**Comment by mccartney** [comment]
@staszek - don't use `[]` brackets for non-links. I suggest you replace them with `()` parentheses

**Comment by staszek** [comment]
> @staszek - don't use `[]` brackets for non-links. I suggest you replace them with `()` parentheses

Good idea, thanks!

**Pull request merged**
