### PR TITLE
Remove Avalara

### PR DESCRIPTION
**Pull request by ghostsquad**
## Remove Avalara

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [x] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

To the best of my knowledge, I don't believe the interview process is consistent enough at Avalara to warrant inclusion.

### CODE REVIEW

**Comment by poteto** [comment]
What do you mean by consistent? Are some of the interview panels heavily CS trivia based?

**Comment by ghostsquad** [comment]
When I was there, a _very_ small group, the Platform SRE team, did interviews without (much) trivia. The company is huge though, lots of teams, and I'm not aware of all the interview practices. Frankly, I think it was a mistake from the beginning to add Avalara to the list because of the fractured culture.

**Comment by ghostsquad** [comment]
This still needs to be merged

**Comment by poteto** [comment]
I'm unsure about merging this because the goal of this repo is to catalog companies that don't do CS based trivia interviews. I acknowledge that your experience there made you feel that the culture was fractured, so sharing that is probably pretty helpful to viewers of this repo. I don't know if that's sufficient enough for removal though.

**Comment by ghostsquad** [comment]
I'm also the one that submitted the PR to add them. Is that enough credibility?

https://github.com/poteto/hiring-without-whiteboards/pull/845/commits/ca70e92d9c0eff9cfeaa1f305263f3a3394ec3f6

**Comment by poteto** [comment]
@ghostsquad Sorry, I didn't realize you added them! My opinion still stands but I'll defer to your experience since you've worked there.

bors r+

**Pull request merged**
