### PR TITLE
Remove Airbnb

### PR DESCRIPTION
**Pull request by poteto**
## Remove Airbnb

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](../CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards#format) prescribed in the readme
- [x] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

Due to a number of people informing me that Airbnb still does use "whiteboard" interviews

### CODE REVIEW

**Comment by poteto** [comment]
cc @alexadusei

**Comment by alexadusei** [comment]
@poteto Hm, that's interesting. During my internship interview process for them, there was no "whiteboarding". My interviewer was an engineer who said something along the lines of "Right now, [this] is currently a problem we're dealing with at AirBnB. Let's open up an editor together and see if we can solve that problem right now for this interview", which is what we did.

If multiple people had experiences that were eminent of the typical "whiteboard-style" however, then I concede, maybe my process was unlike the other ones. Happy to have it removed to better reflect the repo

**Comment by rovolution** [comment]
definitely whiteboarding culture: https://www.glassdoor.com/Interview/Airbnb-Software-Engineer-Interview-Questions-EI_IE391850.0,6_KO7,24.htm

**Comment by poteto** [comment]
I'm going to merge this. If someone from @airbnb chimes in we can revisit adding them back to the list again.

**Pull request merged**
