### PR TITLE
Remove Heap Analytics from list

### PR DESCRIPTION
**Pull request by scalp42**
I was interested at first for an infrastructure role but moved on to other opportunities when I learned about their interview process. Here is a copy of an email I personally sent regarding the interview:

```
Hi [redacted],

I had time to explore other opportunities and at this moment I think having "non trivial algorithms" for a first interview does not align with the vision I have of infrastructure/operations work.

I think you're more looking for a software engineer with a touch of DevOps.

Hopefully it makes sense!

PS: great talks related to modeling PG schemas and challenges.

Anthony
```

Cheers!

### CODE REVIEW

**Comment by poteto** [comment]
@matinm Do you have any thoughts on this?

**Comment by matinm** [comment]
@scalp42 I'm sorry we set the wrong expectations around our infra/devops role! It's indeed more of a software engineering role with a devops bent, rather than the other way around. We try hard to make our interview process as practical/non-contrived as possible (but that doesn't mean algo knowledge is useless, especially for our infrastructure roles). Sounds like there might have been miscommunication here.

@poteto I'm happy to send you more specific context on our interview process in private. Definitely want to ensure we're honoring the spirit of your repo. 😃

**Comment by scalp42** [comment]
@poteto really confused why you closed the PR.

It's still happen to be an interview based on CS questions etc if you're a software engineer.

**Comment by matinm** [comment]
@scalp42 It's not an interview based on CS knowledge. People can (and have) passed our interviews with programming experience but no formal CS background.

Have you been through our process?

**Comment by ckellis** [comment]
@poteto I agree with @scalp42; per the repo requirements in the readme: "Solving basic CS questions, technical puzzles, riddles, brainteasers (with or without whiteboard) is 👎" 

It's pretty clear that there's some bias going on if the discussion about heap's interview process is going to be continued 'privately'. Why not reach out to the actual interviewee to get more details on what exactly he was asked? Sounds like he was given some sort of algo that didn't pertain to real world problems, otherwise he wouldn't have felt compelled to make a PR. 

Practical or not in the eyes of the company mentioned, if there is some sort of CS algo work involved in an infrastructure role, it can't really be adhering to the repo's rules. What worries me is that this PR was closed so quickly without follow-up; this shows me that there's more going on behind the scenes. If you're going to be biased, might as well shut down the repo entirely.

**Comment by scalp42** [comment]
@matinm understand that it's not an attack or anything like against Heap whatsoever.

I'd prefer not giving names as again it doesn't really matter but to give you some insight:

1. had a 60 mins hangout session with one of your recruiters which clearly mentioned that the interview would involve non trivial algorithms (along other things in the same direction that I forgot)
1. I kept the discussion going and was introduced over email to "CTO/first engineer" to set up a time to discuss more
1. I decided that this kind of first interview didn't make a lot of sense for an infrastructure position (had explored other opportunities in the meantime)
1. emailed back that person in question with the email in the PR

Got the following email:

```
[redacted]

I think we say "non trivial algorithms" so people aren't surprised when they are asked something not totally trivial, but I don't think we're looking for anything all that complex on the algorithms side.

[redacted]
```

Again doesn't really matter at the end of the day but it doesn't align with what I understood from this repo @poteto and @matinm.

Hopefully it helps and if not, well PR is closed anyway 🍶 

@ckellis 👍

**Comment by poteto** [comment]
@ckellis @scalp42 To be clear, I did not communicate with @matinm privately. However, if the "whiteboarding CS algo" is a **requirement** of the job, as I presumed from @matinm's comment, then it is OK in my book. I apologize that I didn't actually follow up, so:

@matinm Is algo knowledge a **requirement** of the job?

**Comment by poteto** [comment]
Please see #400 for more details, I am going to merge this for now. We can consider adding Heap back if CS knowledge is mandatory for the job. Thanks to @ckellis and @scalp42 for helping me realize what I'm doing wrongly.

**Comment by scalp42** [comment]
@poteto thanks so much for the transparency!

**Comment by ckellis** [comment]
@scalp42 👍

@poteto agreed, thanks for your quick response and clarification!  Much appreciated ❤️

**Pull request merged**
