### PR TITLE
fix links in PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by adiorion**
## fix internal doc links in PRs

The links in PRs such as #517 don't go to the relevant docs, they just say "Not Found". I don't know how to link from a PR to "a given file in in the current branch" so this PR updates them to point to the `master` branch.

Unfortunately this means that the links are broken in the file view https://github.com/poteto/hiring-without-whiteboards/blob/master/.github/PULL_REQUEST_TEMPLATE.md but I don't think it's possible to get both given current Github limitations?
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](../CODE_OF_CONDUCT.md)
- [x] I have followed the [format](../CONTRIBUTING.md#format) prescribed in the contributing guidelines

### CODE REVIEW

**Comment by kethinov** [comment]
I opened a trivial (pointless) PR to [test this](https://github.com/poteto/hiring-without-whiteboards/pull/526). Looks like it still doesn't work right. Using absolute URLs seems to work though.

**Comment by kethinov** [comment]
Oh duh looks like this isn't merged yet. No wonder it didn't work :O

**Comment by kethinov** [comment]
Yep, it does appear to work. Closed my test PR.

**Comment by poteto** [comment]
Could you use an absolute link instead please? e.g. https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md

**Comment by adiorion** [comment]
@poteto good idea! lemme push that

**Pull request merged**
