### PR TITLE
Remove Ada

### PR DESCRIPTION
**Pull request by coaxial**
- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [x] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

Ada does filter with whiteboarding: candidates are asked to code in a
google docs solutions to abstract algorithms that are unlikely to represent
typical work (for example: write a recursive function that multiplies
two negative numbers together without using the multiply operation)

### CODE REVIEW

**Comment by poteto** [comment]
@RebeccaQu Any comments?

**Comment by RebeccaQu** [comment]
@poteto Ada has changed its hiring process since August, you can remove from this list.

**Comment by coaxial** [comment]
@poteto bump

**Pull request merged**
