### PR TITLE
Remove InQuicker

### PR DESCRIPTION
**Pull request by jc00ke**
They were acquired by a company that decimated the team
and there is no longer any guarantees that a whiteboard
will not be used or that the product will survive.

## Add/Update/Remove <CompanyName>

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [ ] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

### CODE REVIEW

**Comment by dinsley** [comment]
👍

**Comment by Mystryman** [comment]
👍

**Comment by carlin2desautels** [comment]
👍

**Comment by poteto** [comment]
@jc00ke Since you're the same person who added them in the first place, 👍

**Pull request merged**
