### PR TITLE
Added Dragon Cloud

### PR DESCRIPTION
**Pull request by rickmacgillis**
## Add Dragon Cloud

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [ ] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

### CODE REVIEW

**Comment by rickmacgillis** [comment]
Bump

**Comment by mccartney** [comment]
@poteto ?

**Comment by rickmacgillis** [comment]
Please re-merge this PR. For some reason it's missing.

**Comment by rickmacgillis** [comment]
Is anyone planning to maintain this repo?

**Pull request closed without merging**
