### PR TITLE
Update the details for AdWyze

### PR DESCRIPTION
**Pull request by OPhamster**
## Update AdWyze

- [X] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [X] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [X] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [X] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

### Interview Process Updates

  1. Culture and Fit Interview: Over a 30-minute call we will outline the opportunity, review your work experience and look for signs and evidence of culture fit.
  2. Tech Round 1: It covers areas of Coding & DS and Algo.
  3. Tech Round 2: This round covers the Design part
  4. Offer and Closing: Finally you will meet a member of the talent team to close on your compensation details and date of joining. Welcome to Clarisights!

### CODE REVIEW

**Comment by alecdesjardins** [comment]
Does Tech Round 1 include live coding on something like LeetCode?

**Comment by OPhamster** [comment]
> Does Tech Round 1 include live coding on something like LeetCode?

Ah sorry I should have elaborated. No. `Tech Round 1` deals with Data Structures, algorithms and the like in real systems, sometimes systems internally that we have built or tools or systems that already exist. How these adapt to evolving scenarios are usually follow ups.

*None of the interviews use tools/websites like LeetCode or have live coding exercises or any arbitrary competitive programming problems*

image

**Comment by alecdesjardins** [comment]
Sounds good, can you remove the (previously ...) part, and I will merge.

Thanks!

**Comment by OPhamster** [comment]
> Sounds good, can you remove the (previously ...) part, and I will merge.
> 
> Thanks!

done so thanks.

**Pull request merged**
